// A slimmed down version of https://github.com/missive/emoji-mart/blob/main/packages/emoji-mart-data/sets/14/native.json
export const emojiList: { u: string, n: string[] }[] = [
  { u: "1f600", n: ["grinning"] },
  { u: "1f603", n: ["grinning_face_with_big_eyes", "smiley"] },
  { u: "1f604", n: ["grinning_face_with_smiling_eyes", "smile"] },
  { u: "1f601", n: ["beaming_face_with_smiling_eyes", "grin"] },
  { u: "1f606", n: ["grinning_squinting_face", "laughing", "satisfied"] },
  { u: "1f605", n: ["grinning_face_with_sweat", "sweat_smile"] },
  { u: "1f923", n: ["rolling_on_the_floor_laughing"] },
  { u: "1f602", n: ["face_with_tears_of_joy", "joy"] },
  { u: "1f642", n: ["slightly_smiling_face", "slight_smile"] },
  { u: "1f643", n: ["upside_down_face"] },
  { u: "1f609", n: ["winking_face", "wink"] },
  { u: "1f60a", n: ["smiling_face_with_smiling_eyes", "blush"] },
  { u: "1f607", n: ["smiling_face_with_halo", "innocent"] },
  { u: "1f970", n: ["smiling_face_with_3_hearts"] },
  { u: "1f60d", n: ["smiling_face_with_heart-eyes", "heart_eyes"] },
  { u: "1f929", n: ["star-struck"] },
  { u: "1f618", n: ["face_blowing_a_kiss", "kissing_heart"] },
  { u: "1f617", n: ["kissing_face", "kissing"] },
  { u: "263a-fe0f", n: ["smiling_face", "relaxed"] },
  { u: "1f61a", n: ["kissing_face_with_closed_eyes", "kissing_closed_eyes"] },
  { u: "1f619", n: ["kissing_face_with_smiling_eyes"] },
  { u: "1f60b", n: ["face_savoring_food", "yum"] },
  { u: "1f61b", n: ["face_with_tongue"] },
  { u: "1f61c", n: ["winking_face_with_tongue", "stuck_out_tongue_winking_eye"] },
  { u: "1f92a", n: ["zany_face"] },
  { u: "1f61d", n: ["squinting_face_with_tongue", "stuck_out_tongue_closed_eyes"] },
  { u: "1f911", n: ["money-mouth_face"] },
  { u: "1f917", n: ["hugging_face"] },
  { u: "1f92d", n: ["face_with_hand_over_mouth"] },
  { u: "1f92b", n: ["shushing_face"] },
  { u: "1f914", n: ["thinking_face"] },
  { u: "1f910", n: ["zipper-mouth_face"] },
  { u: "1f928", n: ["face_with_raised_eyebrow"] },
  { u: "1f610", n: ["neutral_face"] },
  { u: "1f611", n: ["expressionless_face"] },
  { u: "1f636", n: ["face_without_mouth"] },
  { u: "1f60f", n: ["smirking_face", "smirk"] },
  { u: "1f612", n: ["unamused_face"] },
  { u: "1f644", n: ["face_with_rolling_eyes"] },
  { u: "1f62c", n: ["grimacing_face"] },
  { u: "1f925", n: ["lying_face"] },
  { u: "1f60c", n: ["relieved_face"] },
  { u: "1f614", n: ["pensive_face"] },
  { u: "1f62a", n: ["sleepy_face"] },
  { u: "1f924", n: ["drooling_face"] },
  { u: "1f634", n: ["sleeping_face", "sleeping"] },
  { u: "1f637", n: ["face_with_medical_mask"] },
  { u: "1f912", n: ["face_with_thermometer"] },
  { u: "1f915", n: ["face_with_head-bandage"] },
  { u: "1f922", n: ["nauseated_face"] },
  { u: "1f92e", n: ["face_vomiting"] },
  { u: "1f927", n: ["sneezing_face"] },
  { u: "1f975", n: ["hot_face"] },
  { u: "1f976", n: ["cold_face"] },
  { u: "1f974", n: ["woozy_face"] },
  { u: "1f635", n: ["dizzy_face"] },
  { u: "1f92f", n: ["exploding_head"] },
  { u: "1f920", n: ["cowboy_hat_face"] },
  { u: "1f973", n: ["partying_face"] },
  { u: "1f60e", n: ["smiling_face_with_sunglasses", "sunglasses"] },
  { u: "1f913", n: ["nerd_face"] },
  { u: "1f9d0", n: ["face_with_monocle"] },
  { u: "1f615", n: ["confused_face"] },
  { u: "1f61f", n: ["worried_face"] },
  { u: "1f641", n: ["slightly_frowning_face"] },
  { u: "2639-fe0f", n: ["frowning_face"] },
  { u: "1f62e", n: ["face_with_open_mouth"] },
  { u: "1f62f", n: ["hushed_face"] },
  { u: "1f632", n: ["astonished_face"] },
  { u: "1f633", n: ["flushed_face"] },
  { u: "1f97a", n: ["pleading_face"] },
  { u: "1f626", n: ["frowning_face_with_open_mouth"] },
  { u: "1f627", n: ["anguished_face"] },
  { u: "1f628", n: ["fearful_face"] },
  { u: "1f630", n: ["anxious_face_with_sweat", "cold_sweat"] },
  { u: "1f625", n: ["sad_but_relieved_face"] },
  { u: "1f622", n: ["crying_face", "cry"] },
  { u: "1f62d", n: ["loudly_crying_face", "sob"] },
  { u: "1f631", n: ["face_screaming_in_fear", "scream"] },
  { u: "1f616", n: ["confounded_face"] },
  { u: "1f623", n: ["persevering_face"] },
  { u: "1f61e", n: ["disappointed_face"] },
  { u: "1f613", n: ["downcast_face_with_sweat", "sweat"] },
  { u: "1f629", n: ["weary_face"] },
  { u: "1f62b", n: ["tired_face"] },
  { u: "1f971", n: ["yawning_face"] },
  { u: "1f624", n: ["face_with_steam_from_nose", "triumph"] },
  { u: "1f621", n: ["pouting_face", "rage"] },
  { u: "1f620", n: ["angry_face"] },
  { u: "1f92c", n: ["face_with_symbols_on_mouth"] },
  { u: "1f608", n: ["smiling_face_with_horns"] },
  { u: "1f47f", n: ["angry_face_with_horns"] },
  { u: "1f480", n: ["skull"] },
  { u: "2620-fe0f", n: ["skull_and_crossbones"] },
  { u: "1f4a9", n: ["pile_of_poo"] },
  { u: "1f921", n: ["clown_face"] },
  { u: "1f479", n: ["ogre"] },
  { u: "1f47a", n: ["goblin"] },
  { u: "1f47b", n: ["ghost"] },
  { u: "1f47d", n: ["alien"] },
  { u: "1f47e", n: ["alien_monster"] },
  { u: "1f916", n: ["robot_face"] },
  { u: "1f63a", n: ["grinning_cat_face_with_smiling_eyes", "smiley_cat"] },
  { u: "1f638", n: ["grinning_cat_face_with_smiling_eyes", "smile_cat"] },
  { u: "1f639", n: ["cat_face_with_tears_of_joy", "joy_cat"] },
  { u: "1f63b", n: ["smiling_cat_face_with_heart-eyes", "heart_eyes_cat"] },
  { u: "1f63c", n: ["smirking_cat_face", "smirk_cat"] },
  { u: "1f63d", n: ["kissing_cat_face", "kissing_cat"] },
  { u: "1f640", n: ["weary_cat_face", "scream_cat"] },
  { u: "1f63f", n: ["crying_cat_face", "crying_cat_face"] },
  { u: "1f63e", n: ["pouting_cat_face", "pouting_cat"] },
  { u: "1f648", n: ["see-no-evil_monkey", "see_no_evil"] },
  { u: "1f649", n: ["hear-no-evil_monkey", "hear_no_evil"] },
  { u: "1f64a", n: ["speak-no-evil_monkey", "speak_no_evil"] },
  { u: "1f48b", n: ["kiss_mark", "kiss"] },
  { u: "1f48c", n: ["love_letter"] },
  { u: "1f498", n: ["heart_with_arrow"] },
  { u: "1f49d", n: ["heart_with_ribbon"] },
  { u: "1f496", n: ["sparkling_heart"] },
  { u: "1f497", n: ["growing_heart", "heartpulse"] },
  { u: "1f493", n: ["beating_heart"] },
  { u: "1f49e", n: ["revolving_hearts"] },
  { u: "1f495", n: ["two_hearts"] },
  { u: "1f49f", n: ["heart_decoration"] },
  { u: "2763-fe0f", n: ["heavy_heart_exclamation_mark_ornament"] },
  { u: "1f494", n: ["broken_heart"] },
  { u: "2764-fe0f", n: ["heavy_black_heart", "heart"] },
  { u: "1f9e1", n: ["orange_heart"] },
  { u: "1f49b", n: ["yellow_heart"] },
  { u: "1f49a", n: ["green_heart"] },
  { u: "1f499", n: ["blue_heart"] },
  { u: "1f49c", n: ["purple_heart"] },
  { u: "1f5a4", n: ["black_heart"] },
  { u: "1f4af", n: ["hundred_points", "100"] },
  { u: "1f4a2", n: ["anger_symbol", "anger"] },
  { u: "1f4a5", n: ["collision_symbol", "boom", "collision"] },
  { u: "1f4ab", n: ["dizzy_symbol", "dizzy"] },
  { u: "1f4a6", n: ["splashing_sweat_symbol", "sweat_drops"] },
  { u: "1f4a8", n: ["dash_symbol", "dash"] },
  { u: "1f573-fe0f", n: ["hole"] },
  { u: "1f4a3", n: ["bomb"] },
  { u: "1f4ac", n: ["speech_balloon"] },
  { u: "1f5e8-fe0f", n: ["left_speech_bubble"] },
  { u: "1f5ef-fe0f", n: ["right_anger_bubble"] },
  { u: "1f4ad", n: ["thought_balloon"] },
  { u: "1f4a4", n: ["sleeping_symbol", "zzz"] }
];
